# Deployment and Service for Service A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: service-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# Deployment and Service for Service B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
# Deployment and Service for Service C
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: service-c:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  selector:
    app: service-c
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
# Deployment and Service for Service D
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
      - name: service-d
        image: service-d:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  selector:
    app: service-d
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---
# Deployment and Service for Service E
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-e
  template:
    metadata:
      labels:
        app: service-e
    spec:
      containers:
      - name: service-e
        image: service-e:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: service-e
spec:
  selector:
    app: service-e
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
---
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: load-generator:latest
    imagePullPolicy: Never
    env:
    - name: TARGET_URL
      value: "http://service-a:5000/a"
