# Deployment and Service for Service A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: service-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# Deployment and Service for Service B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
# Deployment and Service for Service C
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: service-c
        image: service-c:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  selector:
    app: service-c
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
# Deployment and Service for Service D
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
      - name: service-d
        image: service-d:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  selector:
    app: service-d
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---
# Deployment and Service for Service E
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-e
  template:
    metadata:
      labels:
        app: service-e
    spec:
      containers:
      - name: service-e
        image: service-e:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: service-e
spec:
  selector:
    app: service-e
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-q
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-q
  template:
    metadata:
      labels:
        app: service-q
    spec:
      containers:
      - name: service-q
        image: service-q:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5007
---
apiVersion: v1
kind: Service
metadata:
  name: service-q
spec:
  selector:
    app: service-q
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-r
  template:
    metadata:
      labels:
        app: service-r
    spec:
      containers:
      - name: service-r
        image: service-r:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: service-r
spec:
  selector:
    app: service-r
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
